
import { Category, WordEntry, Language } from './types';

export const WORD_LIST: Record<Language, Record<string, WordEntry[]>> = {
  [Language.EN]: {
    [Category.GENERAL]: [
      { word: 'Bicycle', imposterClue: 'It relies on individual effort' },
      { word: 'Television', imposterClue: 'A source of shared observation' },
      { word: 'Umbrella', imposterClue: 'Used only in specific conditions' },
      { word: 'Backpack', imposterClue: 'Something that holds your journey' },
      { word: 'Keyboard', imposterClue: 'A tool for creating structure' },
      { word: 'Candle', imposterClue: 'Something that slowly disappears' },
      { word: 'Telescope', imposterClue: 'It brings the distant closer' },
      { word: 'Hammer', imposterClue: 'A tool of impact and force' },
      { word: 'Mirror', imposterClue: 'It shows what is already there' },
      { word: 'Piano', imposterClue: 'A complex system of vibrations' },
      { word: 'Clock', imposterClue: 'A relentless measuring device' },
      { word: 'Scissors', imposterClue: 'It divides what was once whole' },
      { word: 'Wallet', imposterClue: 'A keeper of personal value' },
      { word: 'Battery', imposterClue: 'A container of hidden potential' },
      { word: 'Guitar', imposterClue: 'It requires manual dexterity' },
      { word: 'Soap', imposterClue: 'Something that washes away' },
      { word: 'Camera', imposterClue: 'It stops the flow of time' },
      { word: 'Map', imposterClue: 'A representation of reality' }
    ],
    [Category.MOVIES]: [
      { word: 'Titanic', imposterClue: 'A story of inevitable tragedy' },
      { word: 'Inception', imposterClue: 'A journey through layers of reality' },
      { word: 'Jaws', imposterClue: 'The fear of what lies beneath' },
      { word: 'Avatar', imposterClue: 'A clash between worlds' },
      { word: 'Batman', imposterClue: 'A figure rising from darkness' },
      { word: 'Star Wars', imposterClue: 'An ancient conflict in a new setting' },
      { word: 'Harry Potter', imposterClue: 'A child born for a destiny' },
      { word: 'Toy Story', imposterClue: 'The secret life of the inanimate' },
      { word: 'Jurassic Park', imposterClue: 'Science exceeding its limits' },
      { word: 'The Lion King', imposterClue: 'A cycle of life and leadership' },
      { word: 'Shrek', imposterClue: 'Beauty found in the unusual' },
      { word: 'Gladiator', imposterClue: 'A quest for honor in the dust' },
      { word: 'The Matrix', imposterClue: 'Choosing between truth and comfort' },
      { word: 'Frozen', imposterClue: 'The power of internal coldness' },
      { word: 'Spider-Man', imposterClue: 'Power balanced by duty' }
    ],
    [Category.PLACES]: [
      { word: 'Paris', imposterClue: 'A place of cultural significance' },
      { word: 'Egypt', imposterClue: 'A land of ancient mysteries' },
      { word: 'Tokyo', imposterClue: 'Where the future meets tradition' },
      { word: 'Sydney', imposterClue: 'A landmark by the ocean' },
      { word: 'Hawaii', imposterClue: 'A paradise born from fire' },
      { word: 'London', imposterClue: 'A city built on fog and history' },
      { word: 'New York', imposterClue: 'A vertical forest of concrete' },
      { word: 'Antarctica', imposterClue: 'The edge of the world' },
      { word: 'The Sahara', imposterClue: 'A vast, unforgiving landscape' },
      { word: 'Mars', imposterClue: 'The next frontier for humanity' },
      { word: 'Mount Everest', imposterClue: 'The ultimate physical challenge' },
      { word: 'Great Wall', imposterClue: 'A boundary made of stone' },
      { word: 'Venice', imposterClue: 'A place slowly being reclaimed' },
      { word: 'Hollywood', imposterClue: 'A factory of modern myths' },
      { word: 'Grand Canyon', imposterClue: 'A deep scar in the earth' }
    ],
    [Category.FOOD]: [
      { word: 'Pizza', imposterClue: 'A circle of social experience' },
      { word: 'Sushi', imposterClue: 'Artistisk presentation av raw life' },
      { word: 'Burger', imposterClue: 'A stack of different textures' },
      { word: 'Pancakes', imposterClue: 'A flat, layered indulgence' },
      { word: 'Chocolate', imposterClue: 'A dark, melting pleasure' },
      { word: 'Pasta', imposterClue: 'Versatile forms of dough' },
      { word: 'Salad', imposterClue: 'A collection of earthy harvest' },
      { word: 'Taco', imposterClue: 'A handheld folded delight' },
      { word: 'Steak', imposterClue: 'The centerpiece of the meal' },
      { word: 'Soup', imposterClue: 'A comforting blend of liquids' },
      { word: 'Donut', imposterClue: 'A sweet void in the center' },
      { word: 'Bacon', imposterClue: 'The aroma of the morning' },
      { word: 'Popcorn', imposterClue: 'Transforming under high heat' },
      { word: 'Cheese', imposterClue: 'Patiently aged and transformed' },
      { word: 'Ice Cream', imposterClue: 'A temporary frozen joy' }
    ],
    [Category.ANIMALS]: [
      { word: 'Elephant', imposterClue: 'A creature of long memory' },
      { word: 'Giraffe', imposterClue: 'A perspective from above' },
      { word: 'Penguin', imposterClue: 'Adaptation to extreme environments' },
      { word: 'Kangaroo', imposterClue: 'Unique movement across land' },
      { word: 'Octopus', imposterClue: 'Alien intelligence in the sea' },
      { word: 'Lion', imposterClue: 'The pinnacle of the hierarchy' },
      { word: 'Shark', imposterClue: 'A perfect evolutionary hunter' },
      { word: 'Eagle', imposterClue: 'Vigilance from the heights' },
      { word: 'Snake', imposterClue: 'A silent, low-lying predator' },
      { word: 'Horse', imposterClue: 'A companion to human progress' },
      { word: 'Bee', imposterClue: 'Hard work for the collective' },
      { word: 'Owl', imposterClue: 'Wisdom hidden in darkness' },
      { word: 'Wolf', imposterClue: 'Loyalty to the group' },
      { word: 'Whale', imposterClue: 'A giant in a vast world' },
      { word: 'Spider', imposterClue: 'A weaver of intricate traps' }
    ],
    [Category.SPORTS]: [
      { word: 'Football', imposterClue: 'A contest of territorial gain' },
      { word: 'Tennis', imposterClue: 'A back-and-forth duel' },
      { word: 'Golf', imposterClue: 'A quest for precision in nature' },
      { word: 'Basketball', imposterClue: 'A game of vertical reach' },
      { word: 'Swimming', imposterClue: 'Movement through resistance' },
      { word: 'Baseball', imposterClue: 'Patient cycles of play' },
      { word: 'Boxing', imposterClue: 'The art of the direct hit' },
      { word: 'Skiing', imposterClue: 'Gliding down natural slopes' },
      { word: 'Surfing', imposterClue: 'Harnessing the power of waves' },
      { word: 'Cricket', imposterClue: 'A game of long strategy' },
      { word: 'Rugby', imposterClue: 'Rough power and teamwork' },
      { word: 'Archery', imposterClue: 'Focusing on a single point' },
      { word: 'Cycling', imposterClue: 'Human endurance on two wheels' },
      { word: 'Hockey', imposterClue: 'High-speed motion on a surface' },
      { word: 'Yoga', imposterClue: 'A balance of mind and body' }
    ],
    [Category.FANTASY]: [
      { word: 'Dragon', imposterClue: 'The ultimate hoard keeper' },
      { word: 'Wizard', imposterClue: 'Mastery over the unseen' },
      { word: 'Castle', imposterClue: 'A symbol of power and defense' },
      { word: 'Elf', imposterClue: 'Elegance and long life' },
      { word: 'Sword', imposterClue: 'A blade of destiny' },
      { word: 'Potion', imposterClue: 'Liquid magic in a bottle' },
      { word: 'Unicorn', imposterClue: 'Rarity and pure light' },
      { word: 'Vampire', imposterClue: 'A curse of eternal thirst' },
      { word: 'Werewolf', imposterClue: 'Duality within the self' },
      { word: 'Ghost', imposterClue: 'A remnant of the past' }
    ],
    [Category.JOBS]: [
      { word: 'Doctor', imposterClue: 'Healing through knowledge' },
      { word: 'Pilot', imposterClue: 'Commanding the heights' },
      { word: 'Chef', imposterClue: 'Creation through heat' },
      { word: 'Artist', imposterClue: 'Expressing the internal' },
      { word: 'Firefighter', imposterClue: 'Facing the dangerous elements' },
      { word: 'Teacher', imposterClue: 'Molding the future minds' },
      { word: 'Police', imposterClue: 'Maintaining order in chaos' },
      { word: 'Farmer', imposterClue: 'Working with the seasons' },
      { word: 'Astronaut', imposterClue: 'Leaving the world behind' },
      { word: 'Scientist', imposterClue: 'Testing the rules of nature' }
    ],
    [Category.BRANDS]: [
      { word: 'Apple', imposterClue: 'Simplicity and sleek design' },
      { word: 'Nike', imposterClue: 'Motivation to keep moving' },
      { word: 'Google', imposterClue: 'Information at your fingertips' },
      { word: 'Coca-Cola', imposterClue: 'A taste known everywhere' },
      { word: 'Starbucks', imposterClue: 'A community gathering spot' },
      { word: 'Tesla', imposterClue: 'Innovation for the future' },
      { word: 'Amazon', imposterClue: 'The world delivered to you' },
      { word: 'Netflix', imposterClue: 'Infinite stories to watch' },
      { word: 'McDonalds', imposterClue: 'Consistency and fast service' },
      { word: 'Disney', imposterClue: 'Magic for all generations' }
    ]
  },
  [Language.SV]: {
    [Category.GENERAL]: [
      { word: 'Cykel', imposterClue: 'Den förlitar sig på individuell ansträngning' },
      { word: 'TV', imposterClue: 'En källa till gemensam observation' },
      { word: 'Paraply', imposterClue: 'Används endast under specifika förhållanden' },
      { word: 'Ryggsäck', imposterClue: 'Något som rymmer din resa' },
      { word: 'Tangentbord', imposterClue: 'Ett verktyg för att skapa struktur' },
      { word: 'Ljus', imposterClue: 'Något som sakta försvinner' },
      { word: 'Teleskop', imposterClue: 'Det för det avlägsna närmare' },
      { word: 'Hammare', imposterClue: 'Ett verktyg för kraft och anslag' },
      { word: 'Spegel', imposterClue: 'Den visar vad som redan finns där' },
      { word: 'Piano', imposterClue: 'Ett komplext system av vibrationer' },
      { word: 'Klocka', imposterClue: 'En obeveklig mätenhet' },
      { word: 'Sax', imposterClue: 'Den delar det som en gång var helt' },
      { word: 'Plånbok', imposterClue: 'En väktare av personligt värde' },
      { word: 'Batteri', imposterClue: 'En behållare av dold potential' },
      { word: 'Gitarr', imposterClue: 'Den kräver manuell fingerfärdighet' },
      { word: 'Tvål', imposterClue: 'Något som sköljer bort' },
      { word: 'Kamera', imposterClue: 'Den stoppar tidens flöde' },
      { word: 'Karta', imposterClue: 'En representation av verkligheten' }
    ],
    [Category.MOVIES]: [
      { word: 'Titanic', imposterClue: 'En berättelse om oundviklig tragedi' },
      { word: 'Inception', imposterClue: 'En resa genom lager av verklighet' },
      { word: 'Hajen', imposterClue: 'Rädslan för vad som finns under ytan' },
      { word: 'Avatar', imposterClue: 'En krock mellan världar' },
      { word: 'Batman', imposterClue: 'En figur som reser sig ur mörkret' },
      { word: 'Star Wars', imposterClue: 'En gammal konflikt i en ny miljö' },
      { word: 'Harry Potter', imposterClue: 'Ett barn fött för ett öde' },
      { word: 'Toy Story', imposterClue: 'Det hemliga livet hos det livlösa' },
      { word: 'Jurassic Park', imposterClue: 'Vetenskap som överskrider sina gränser' },
      { word: 'Lejonkungen', imposterClue: 'En cirkel av liv och ledarskap' },
      { word: 'Shrek', imposterClue: 'Skönhet funnen i det ovanliga' },
      { word: 'Gladiator', imposterClue: 'En jakt på ära i dammet' },
      { word: 'The Matrix', imposterClue: 'Välja mellan sanning och komfort' },
      { word: 'Frost', imposterClue: 'Kraften i inre kyla' },
      { word: 'Spider-Man', imposterClue: 'Kraft balanserad av plikt' }
    ],
    [Category.PLACES]: [
      { word: 'Paris', imposterClue: 'En plats av kulturell betydelse' },
      { word: 'Egypten', imposterClue: 'Ett land av forntida mysterier' },
      { word: 'Tokyo', imposterClue: 'Där framtiden möter traditionen' },
      { word: 'Sydney', imposterClue: 'Ett landmärke vid havet' },
      { word: 'Hawaii', imposterClue: 'Ett paradis fött ur eld' },
      { word: 'London', imposterClue: 'En stad byggd på dimma och historia' },
      { word: 'New York', imposterClue: 'En vertikal skog av betong' },
      { word: 'Antarktis', imposterClue: 'Världens ände' },
      { word: 'Sahara', imposterClue: 'Ett vidsträckt, oförlåtande landskap' },
      { word: 'Mars', imposterClue: 'Mänsklighetens nästa gräns' },
      { word: 'Mount Everest', imposterClue: 'Den ultimata fysiska utmaningen' },
      { word: 'Kinesiska muren', imposterClue: 'En gräns gjord av sten' },
      { word: 'Venedig', imposterClue: 'En plats som sakta återtas' },
      { word: 'Hollywood', imposterClue: 'En fabrik för moderna myter' },
      { word: 'Grand Canyon', imposterClue: 'Ett djupt ärr i jorden' }
    ],
    [Category.FOOD]: [
      { word: 'Pizza', imposterClue: 'En cirkel av social erfarenhet' },
      { word: 'Sushi', imposterClue: 'Artistisk presentation av rått liv' },
      { word: 'Burgare', imposterClue: 'En stapel av olika texturer' },
      { word: 'Pannkakor', imposterClue: 'En platt, lager-på-lager njutning' },
      { word: 'Choklad', imposterClue: 'En mörk, smältande njutning' },
      { word: 'Pasta', imposterClue: 'Mångsidiga former av deg' },
      { word: 'Sallad', imposterClue: 'En samling jordig skörd' },
      { word: 'Taco', imposterClue: 'En handhållen vikt läckerhet' },
      { word: 'Stek', imposterClue: 'Måltidens medelpunkt' },
      { word: 'Soppa', imposterClue: 'En tröstande blandning av vätskor' },
      { word: 'Munk', imposterClue: 'Ett sött tomrum i mitten' },
      { word: 'Bacon', imposterClue: 'Morgonens doft' },
      { word: 'Popcorn', imposterClue: 'Förvandlas under hög värme' },
      { word: 'Ost', imposterClue: 'Tålmodigt lagrad och förvandlad' },
      { word: 'Glass', imposterClue: 'En tillfällig frusen glädje' }
    ],
    [Category.ANIMALS]: [
      { word: 'Elefant', imposterClue: 'En varelse med långt minne' },
      { word: 'Giraff', imposterClue: 'Ett perspektiv ovanifrån' },
      { word: 'Pingvin', imposterClue: 'Anpassning till extrema miljöer' },
      { word: 'Känguru', imposterClue: 'Unik rörelse över land' },
      { word: 'Bläckfisk', imposterClue: 'Utomjordisk intelligens i havet' },
      { word: 'Lejon', imposterClue: 'Hierarkins höjdpunkt' },
      { word: 'Haj', imposterClue: 'En perfekt evolutionär jägare' },
      { word: 'Örn', imposterClue: 'Vaksamhet från höjderna' },
      { word: 'Orm', imposterClue: 'Ett tyst, låglänt rovdjur' },
      { word: 'Häst', imposterClue: 'En följeslagare till mänskliga framsteg' },
      { word: 'Bi', imposterClue: 'Hårt arbete för kollektivet' },
      { word: 'Uggla', imposterClue: 'Visdom dold i mörkret' },
      { word: 'Varg', imposterClue: 'Lojalitet mot gruppen' },
      { word: 'Val', imposterClue: 'En jätte i en vidsträckt värld' },
      { word: 'Spindel', imposterClue: 'En vävare av intrikata fällor' }
    ],
    [Category.SPORTS]: [
      { word: 'Fotboll', imposterClue: 'En tävling om territoriell vinst' },
      { word: 'Tennis', imposterClue: 'En fram-och-tillbaka duell' },
      { word: 'Golf', imposterClue: 'En jakt på precision i naturen' },
      { word: 'Basket', imposterClue: 'Ett spel med vertikal räckvidd' },
      { word: 'Simning', imposterClue: 'Rörelse genom motstånd' },
      { word: 'Baseboll', imposterClue: 'Tålmodiga cykler av spel' },
      { word: 'Boxning', imposterClue: 'Konsten att få en direktträff' },
      { word: 'Skidåkning', imposterClue: 'Glida nerför naturliga sluttningar' },
      { word: 'Surfing', imposterClue: 'Tämja vågornas kraft' },
      { word: 'Cricket', imposterClue: 'Ett spel av lång strategi' },
      { word: 'Rugby', imposterClue: 'Rå kraft och lagarbete' },
      { word: 'Bågskytte', imposterClue: 'Fokusera på en enda punkt' },
      { word: 'Cykling', imposterClue: 'Mänsklig uthållighet på två hjul' },
      { word: 'Is hockey', imposterClue: 'Höghastighetsrörelse på en yta' },
      { word: 'Yoga', imposterClue: 'En balans mellan kropp och sinne' }
    ],
    [Category.FANTASY]: [
      { word: 'Drake', imposterClue: 'Den ultimata skattväktaren' },
      { word: 'Trollkarl', imposterClue: 'Mästerskap över det osedda' },
      { word: 'Slott', imposterClue: 'En symbol för makt och försvar' },
      { word: 'Alv', imposterClue: 'Elegans och långt liv' },
      { word: 'Svärd', imposterClue: 'Ett ödets klinga' },
      { word: 'Trolldryck', imposterClue: 'Flytande magi i en flaska' },
      { word: 'Enhörning', imposterClue: 'Sällsynthet och rent ljus' },
      { word: 'Vampyr', imposterClue: 'En förbannelse av evig törst' },
      { word: 'Varulv', imposterClue: 'Dualitet inom jaget' },
      { word: 'Spöke', imposterClue: 'En rest från det förflutna' }
    ],
    [Category.JOBS]: [
      { word: 'Läkare', imposterClue: 'Läkning genom kunskap' },
      { word: 'Pilot', imposterClue: 'Befäl över höjderna' },
      { word: 'Kock', imposterClue: 'Skapande genom värme' },
      { word: 'Konstnär', imposterClue: 'Uttrycka det inre' },
      { word: 'Brandman', imposterClue: 'Möta de farliga elementen' },
      { word: 'Lärare', imposterClue: 'Forma framtidens sinnen' },
      { word: 'Polis', imposterClue: 'Upprätthålla ordning i kaos' },
      { word: 'Bonde', imposterClue: 'Arbeta med årstiderna' },
      { word: 'Astronaut', imposterClue: 'Lämna världen bakom sig' },
      { word: 'Forskare', imposterClue: 'Testa naturens regler' }
    ],
    [Category.BRANDS]: [
      { word: 'Apple', imposterClue: 'Enkelhet och elegant design' },
      { word: 'Nike', imposterClue: 'Motivation att fortsätta röra sig' },
      { word: 'Google', imposterClue: 'Information vid dina fingertoppar' },
      { word: 'Coca-Cola', imposterClue: 'En smak känd överallt' },
      { word: 'Starbucks', imposterClue: 'En samlingsplats för samhället' },
      { word: 'Tesla', imposterClue: 'Innovation för framtiden' },
      { word: 'Amazon', imposterClue: 'Världen levererad till dig' },
      { word: 'Netflix', imposterClue: 'Oändliga historier att titta på' },
      { word: 'McDonalds', imposterClue: 'Konsekvens och snabb service' },
      { word: 'Disney', imposterClue: 'Magi för alla generationer' }
    ]
  },
  [Language.FR]: {
    [Category.GENERAL]: [
      { word: 'Vélo', imposterClue: 'Cela repose sur un effort individuel' },
      { word: 'Télévision', imposterClue: 'Une source d\'observation partagée' },
      { word: 'Parapluie', imposterClue: 'Utilisé uniquement dans des conditions spécifiques' },
      { word: 'Sac à dos', imposterClue: 'Quelque chose qui contient votre voyage' },
      { word: 'Clavier', imposterClue: 'Un outil pour créer une structure' },
      { word: 'Bougie', imposterClue: 'Quelque chose qui disparaît lentement' },
      { word: 'Télescope', imposterClue: 'Il rapproche le lointain' },
      { word: 'Marteau', imposterClue: 'Un outil d\'impact et de force' },
      { word: 'Miroir', imposterClue: 'Il montre ce qui est déjà là' },
      { word: 'Piano', imposterClue: 'Un système complexe de vibrations' },
      { word: 'Horloge', imposterClue: 'Un appareil de mesure incessant' },
      { word: 'Ciseaux', imposterClue: 'Il divise ce qui était autrefois entier' },
      { word: 'Portefeuille', imposterClue: 'Un gardien de valeur personnelle' },
      { word: 'Batterie', imposterClue: 'Un conteneur de potentiel caché' },
      { word: 'Guitare', imposterClue: 'Cela nécessite une dextérité manuelle' },
      { word: 'Savon', imposterClue: 'Quelque chose qui s\'en va au lavage' },
      { word: 'Appareil photo', imposterClue: 'Il arrête le flux du temps' },
      { word: 'Carte', imposterClue: 'Une représentation de la réalité' }
    ],
    [Category.MOVIES]: [
      { word: 'Titanic', imposterClue: 'Une histoire de tragédie inévitable' },
      { word: 'Inception', imposterClue: 'Un voyage à travers des couches de réalité' },
      { word: 'Les Dents de la mer', imposterClue: 'La peur de ce qui se cache en dessous' },
      { word: 'Avatar', imposterClue: 'Un conflit entre les mondes' },
      { word: 'Batman', imposterClue: 'Un personnage s\'élevant des ténèbres' },
      { word: 'Star Wars', imposterClue: 'Un conflit ancien dans un nouveau décor' },
      { word: 'Harry Potter', imposterClue: 'Un enfant né pour un destin' },
      { word: 'Toy Story', imposterClue: 'La vie secrète de l\'inanimé' },
      { word: 'Jurassic Park', imposterClue: 'La science dépassant ses limites' },
      { word: 'Le Roi Lion', imposterClue: 'Un cycle de vie et de leadership' },
      { word: 'Shrek', imposterClue: 'La beauté trouvée dans l\'insolite' },
      { word: 'Gladiator', imposterClue: 'Une quête d\'honneur dans la poussière' },
      { word: 'Matrix', imposterClue: 'Choisir entre la vérité et le confort' },
      { word: 'La Reine des neiges', imposterClue: 'Le pouvoir du froid interne' },
      { word: 'Spider-Man', imposterClue: 'Le pouvoir équilibré par le devoir' }
    ],
    [Category.PLACES]: [
      { word: 'Paris', imposterClue: 'Un lieu d\'importance culturelle' },
      { word: 'Égypte', imposterClue: 'Une terre de mystères anciens' },
      { word: 'Tokyo', imposterClue: 'Où le futur rencontre la tradition' },
      { word: 'Sydney', imposterClue: 'Un point de repère au bord de l\'océan' },
      { word: 'Hawaï', imposterClue: 'Un paradis né du feu' },
      { word: 'Londres', imposterClue: 'Une ville bâtie sur le brouillard et l\'histoire' },
      { word: 'New York', imposterClue: 'Une forêt verticale de béton' },
      { word: 'Antarctique', imposterClue: 'Le bout du monde' },
      { word: 'Le Sahara', imposterClue: 'Un vaste paysage impitoyable' },
      { word: 'Mars', imposterClue: 'La prochaine frontière pour l\'humanité' },
      { word: 'Mont Everest', imposterClue: 'Le défi physique ultime' },
      { word: 'Grande Muraille', imposterClue: 'Une frontière faite de pierre' },
      { word: 'Venise', imposterClue: 'Un lieu lentement reconquis' },
      { word: 'Hollywood', imposterClue: 'Une fabrique de mythes modernes' },
      { word: 'Grand Canyon', imposterClue: 'Une cicatrice profonde dans la terre' }
    ],
    [Category.FOOD]: [
      { word: 'Pizza', imposterClue: 'Un cercle d\'expérience sociale' },
      { word: 'Sushi', imposterClue: 'Présentation artistique de la vie brute' },
      { word: 'Burger', imposterClue: 'Un empilement de textures différentes' },
      { word: 'Crêpes', imposterClue: 'Une indulgence plate et superposée' },
      { word: 'Chocolat', imposterClue: 'Un plaisir sombre et fondant' },
      { word: 'Pâtes', imposterClue: 'Formes polyvalentes de pâte' },
      { word: 'Salade', imposterClue: 'Une collection de récoltes terreuses' },
      { word: 'Taco', imposterClue: 'Un délice plié à la main' },
      { word: 'Steak', imposterClue: 'La pièce maîtresse du repas' },
      { word: 'Soupe', imposterClue: 'Un mélange réconfortant de liquides' },
      { word: 'Donut', imposterClue: 'Un vide sucré au centre' },
      { word: 'Bacon', imposterClue: 'L\'arôme du matin' },
      { word: 'Popcorn', imposterClue: 'Se transformant sous une forte chaleur' },
      { word: 'Fromage', imposterClue: 'Patiemment vieilli et transformé' },
      { word: 'Glace', imposterClue: 'Une joie gelée temporaire' }
    ],
    [Category.ANIMALS]: [
      { word: 'Éléphant', imposterClue: 'Une créature de longue mémoire' },
      { word: 'Girafe', imposterClue: 'Une perspective d\'en haut' },
      { word: 'Pingouin', imposterClue: 'Adaptation à des environnements extrêmes' },
      { word: 'Kangourou', imposterClue: 'Mouvement unique à travers la terre' },
      { word: 'Poulpe', imposterClue: 'Intelligence extraterrestre dans la mer' },
      { word: 'Lion', imposterClue: 'Le sommet de la hiérarchie' },
      { word: 'Requin', imposterClue: 'Un chasseur évolutif parfait' },
      { word: 'Aigle', imposterClue: 'Vigilance depuis les hauteurs' },
      { word: 'Serpent', imposterClue: 'Un prédateur silencieux et bas' },
      { word: 'Cheval', imposterClue: 'Un compagnon du progrès humain' },
      { word: 'Abeille', imposterClue: 'Travail acharné pour le collectif' },
      { word: 'Hibou', imposterClue: 'Sagesse cachée dans les ténèbres' },
      { word: 'Loup', imposterClue: 'Loyauté envers le groupe' },
      { word: 'Baleine', imposterClue: 'Un géant dans un monde vaste' },
      { word: 'Araignée', imposterClue: 'Un tisserand de pièges complexes' }
    ],
    [Category.SPORTS]: [
      { word: 'Football', imposterClue: 'Un concours de gain territorial' },
      { word: 'Tennis', imposterClue: 'Un duel de va-et-vient' },
      { word: 'Golf', imposterClue: 'Une quête de précision dans la nature' },
      { word: 'Basket-ball', imposterClue: 'Un jeu de portée verticale' },
      { word: 'Natation', imposterClue: 'Mouvement à travers la résistance' },
      { word: 'Baseball', imposterClue: 'Cycles de jeu patients' },
      { word: 'Boxe', imposterClue: 'L\'art du coup direct' },
      { word: 'Ski', imposterClue: 'Glisser sur des pentes naturelles' },
      { word: 'Surf', imposterClue: 'Exploiter la puissance des vagues' },
      { word: 'Cricket', imposterClue: 'Un jeu de longue stratégie' },
      { word: 'Rugby', imposterClue: 'Puissance brute et travail d\'équipe' },
      { word: 'Tir à l\'arc', imposterClue: 'Se concentrer sur un seul point' },
      { word: 'Cyclisme', imposterClue: 'Endurance humaine sur deux roues' },
      { word: 'Hockey', imposterClue: 'Mouvement à grande vitesse sur une surface' },
      { word: 'Yoga', imposterClue: 'Un équilibre de l\'esprit et du corps' }
    ],
    [Category.FANTASY]: [
      { word: 'Dragon', imposterClue: 'Le gardien ultime du trésor' },
      { word: 'Sorcier', imposterClue: 'Maîtrise de l\'invisible' },
      { word: 'Château', imposterClue: 'Un symbole de pouvoir et de défense' },
      { word: 'Elfe', imposterClue: 'Élégance et longue vie' },
      { word: 'Épée', imposterClue: 'Une lame de destin' },
      { word: 'Potion', imposterClue: 'Magie liquide en bouteille' },
      { word: 'Licorne', imposterClue: 'Rareté et pure lumière' },
      { word: 'Vampire', imposterClue: 'Une malédiction de soif éternelle' },
      { word: 'Loup-garou', imposterClue: 'Dualité en soi' },
      { word: 'Fantôme', imposterClue: 'Un vestige du passé' }
    ],
    [Category.JOBS]: [
      { word: 'Docteur', imposterClue: 'Guérir par la connaissance' },
      { word: 'Pilote', imposterClue: 'Commander les hauteurs' },
      { word: 'Chef', imposterClue: 'Création par la chaleur' },
      { word: 'Artiste', imposterClue: 'Exprimer l\'interne' },
      { word: 'Pompier', imposterClue: 'Faire face aux éléments dangereux' },
      { word: 'Professeur', imposterClue: 'Façonner les esprits futurs' },
      { word: 'Police', imposterClue: 'Maintenir l\'ordre dans le chaos' },
      { word: 'Fermier', imposterClue: 'Travailler avec les saisons' },
      { word: 'Astronaute', imposterClue: 'Laisser le monde derrière soi' },
      { word: 'Scientifique', imposterClue: 'Tester les règles de la nature' }
    ],
    [Category.BRANDS]: [
      { word: 'Apple', imposterClue: 'Simplicité et design épuré' },
      { word: 'Nike', imposterClue: 'Motivation pour continuer à bouger' },
      { word: 'Google', imposterClue: 'L\'information à portée de main' },
      { word: 'Coca-Cola', imposterClue: 'Un goût connu partout' },
      { word: 'Starbucks', imposterClue: 'Un lieu de rassemblement communautaire' },
      { word: 'Tesla', imposterClue: 'Innovation pour le futur' },
      { word: 'Amazon', imposterClue: 'Le monde livré chez vous' },
      { word: 'Netflix', imposterClue: 'Des histoires infinies à regarder' },
      { word: 'McDonalds', imposterClue: 'Cohérence et service rapide' },
      { word: 'Disney', imposterClue: 'La magie pour toutes les générations' }
    ]
  },
  [Language.ZH]: {
    [Category.GENERAL]: [
      { word: '自行车', imposterClue: '这取决于个人的努力' },
      { word: '电视', imposterClue: '共同观察的来源' },
      { word: '雨伞', imposterClue: '仅在特定条件下使用' },
      { word: '背包', imposterClue: '承载你旅程的东西' },
      { word: '键盘', imposterClue: '创建结构的工具' },
      { word: '蜡烛', imposterClue: '慢慢消失的东西' },
      { word: '望远镜', imposterClue: '它让远处变近' },
      { word: '锤子', imposterClue: '冲击和力量的工具' },
      { word: '镜子', imposterClue: '它显示已经存在的东西' },
      { word: '钢琴', imposterClue: '一个复杂的振动系统' },
      { word: '时钟', imposterClue: '一个无情的测量设备' },
      { word: '剪刀', imposterClue: '它将曾经完整的东西分开' },
      { word: '钱包', imposterClue: '个人价值的守护者' },
      { word: '电池', imposterClue: '隐藏潜力的容器' },
      { word: '吉他', imposterClue: '它需要手部灵巧' },
      { word: '肥皂', imposterClue: '洗掉的东西' },
      { word: '相机', imposterClue: '它停止时间的流动' },
      { word: '地图', imposterClue: '现实的呈现' }
    ],
    [Category.MOVIES]: [
      { word: '泰坦尼克号', imposterClue: '一个不可避免的悲剧故事' },
      { word: '盗梦空间', imposterClue: '穿越现实层面的旅程' },
      { word: '大白鲨', imposterClue: '对潜伏在下方东西的恐惧' },
      { word: '阿凡达', imposterClue: '世界之间的冲突' },
      { word: '蝙蝠侠', imposterClue: '一个从黑暗中崛起的形象' },
      { word: '星球大战', imposterClue: '新环境中发生的古老冲突' },
      { word: '哈利波特', imposterClue: '为命运而生的孩子' },
      { word: '玩具总动员', imposterClue: '无生命物体的秘密生活' },
      { word: '侏罗纪公园', imposterClue: '科学超越了它的极限' },
      { word: '狮子王', imposterClue: '生命和领导力的循环' },
      { word: '史瑞克', imposterClue: '在不寻常中发现的美' },
      { word: '角斗士', imposterClue: '在尘土中追求荣誉' },
      { word: '黑客帝国', imposterClue: '在真相和舒适之间做出选择' },
      { word: '冰雪奇缘', imposterClue: '内在寒冷的力量' },
      { word: '蜘蛛侠', imposterClue: '被责任平衡的力量' }
    ],
    [Category.PLACES]: [
      { word: '巴黎', imposterClue: '具有文化意义的地方' },
      { word: '埃及', imposterClue: '古老神秘的土地' },
      { word: '东京', imposterClue: '未来与传统交汇的地方' },
      { word: '悉尼', imposterClue: '海边的一个地标' },
      { word: '夏威夷', imposterClue: '火中诞生的天堂' },
      { word: '伦敦', imposterClue: '一座建立在雾和历史之上的城市' },
      { word: '纽约', imposterClue: '混凝土构成的垂直森林' },
      { word: '南极洲', imposterClue: '世界的尽头' },
      { word: '撒哈拉沙漠', imposterClue: '广阔而严酷的地貌' },
      { word: '火星', imposterClue: '人类的下一个前沿' },
      { word: '珠穆朗玛峰', imposterClue: '终极的身体挑战' },
      { word: '长城', imposterClue: '用石头做成的边界' },
      { word: '威尼斯', imposterClue: '一个慢慢被收回的地方' },
      { word: '好莱坞', imposterClue: '现代神话的工厂' },
      { word: '大峡谷', imposterClue: '地球上的一道深痕' }
    ],
    [Category.FOOD]: [
      { word: '比萨', imposterClue: '社交体验的一个圈子' },
      { word: '寿司', imposterClue: '原始生命的艺术呈现' },
      { word: '汉堡', imposterClue: '不同质地的堆叠' },
      { word: '煎饼', imposterClue: '平坦、分层的放纵' },
      { word: '巧克力', imposterClue: '黑暗、融化的快乐' },
      { word: '面条', imposterClue: '多功能的面团形式' },
      { word: '沙拉', imposterClue: '大地收获的集合' },
      { word: '塔可', imposterClue: '手持折叠的美味' },
      { word: '牛排', imposterClue: '这顿饭的核心' },
      { word: '汤', imposterClue: '舒适的液体混合物' },
      { word: '甜甜圈', imposterClue: '中心的一个甜美的空洞' },
      { word: '培根', imposterClue: '清晨的香气' },
      { word: '爆米花', imposterClue: '在高热下转化' },
      { word: '奶酪', imposterClue: '耐心陈化和转化' },
      { word: '冰淇淋', imposterClue: '暂时的冷冻喜悦' }
    ],
    [Category.ANIMALS]: [
      { word: '大象', imposterClue: '记忆力很长的生物' },
      { word: '长颈鹿', imposterClue: '居高临下的视角' },
      { word: '企鹅', imposterClue: '适应极端环境' },
      { word: '袋鼠', imposterClue: '独特的陆地运动方式' },
      { word: '章鱼', imposterClue: '海洋中的外星智慧' },
      { word: '狮子', imposterClue: '等级制度的顶峰' },
      { word: '鲨鱼', imposterClue: '完美的进化猎人' },
      { word: '鹰', imposterClue: '来自高处的警惕' },
      { word: '蛇', imposterClue: '沉默、低垂的掠食者' },
      { word: '马', imposterClue: '人类进步的伙伴' },
      { word: '蜜蜂', imposterClue: '为集体辛勤工作' },
      { word: '猫头鹰', imposterClue: '隐藏在黑暗中的智慧' },
      { word: '狼', imposterClue: '对群体的忠诚' },
      { word: '鲸鱼', imposterClue: '广阔世界中的巨人' },
      { word: '蜘蛛', imposterClue: '复杂陷阱的编织者' }
    ],
    [Category.SPORTS]: [
      { word: '足球', imposterClue: '领土获取的竞争' },
      { word: '网球', imposterClue: '来回的对决' },
      { word: '高尔夫', imposterClue: '在自然中追求精准' },
      { word: '篮球', imposterClue: '垂直延伸的游戏' },
      { word: '游泳', imposterClue: '穿越阻力的运动' },
      { word: '棒球', imposterClue: '耐心的比赛周期' },
      { word: '拳击', imposterClue: '直接命中的艺术' },
      { word: '滑雪', imposterClue: '在自然坡道上滑行' },
      { word: '冲浪', imposterClue: '利用海浪的力量' },
      { word: '板球', imposterClue: '长线策略的游戏' },
      { word: '橄榄球', imposterClue: '粗犷的力量和团队合作' },
      { word: '射箭', imposterClue: '专注于单点' },
      { word: '自行车', imposterClue: '两个轮子上的耐力挑战' },
      { word: '冰球', imposterClue: '冰面上的高速运动' },
      { word: '瑜伽', imposterClue: '身心的平衡' }
    ],
    [Category.FANTASY]: [
      { word: '巨龙', imposterClue: '终极的宝藏看守者' },
      { word: '巫师', imposterClue: '对无形事物的掌握' },
      { word: '城堡', imposterClue: '权力和防御的象征' },
      { word: '精灵', imposterClue: '优雅和长寿' },
      { word: '宝剑', imposterClue: '命运之刃' },
      { word: '药水', imposterClue: '瓶中的液体魔法' },
      { word: '独角兽', imposterClue: '稀有和纯净的光' },
      { word: '吸血鬼', imposterClue: '永恒渴求的诅咒' },
      { word: '狼人', imposterClue: '内在的双重性' },
      { word: '幽灵', imposterClue: '过去的残余' }
    ],
    [Category.JOBS]: [
      { word: '医生', imposterClue: '通过知识治愈' },
      { word: '飞行员', imposterClue: '指挥高度' },
      { word: '厨师', imposterClue: '通过热量创造' },
      { word: '艺术家', imposterClue: '表达内在' },
      { word: '消防员', imposterClue: '面对危险元素' },
      { word: '教师', imposterClue: '塑造未来的思想' },
      { word: '警察', imposterClue: '在混乱中维持秩序' },
      { word: '农民', imposterClue: '随季节劳作' },
      { word: '宇航员', imposterClue: '离开这个世界' },
      { word: '科学家', imposterClue: '测试自然规律' }
    ],
    [Category.BRANDS]: [
      { word: '苹果', imposterClue: '简单和时尚的设计' },
      { word: '耐克', imposterClue: '保持运动的动力' },
      { word: '谷歌', imposterClue: '触手可及的信息' },
      { word: '可口可乐', imposterClue: '到处都为人熟知的味道' },
      { word: '星巴克', imposterClue: '社区聚集地' },
      { word: '特斯拉', imposterClue: '面向未来的创新' },
      { word: '亚马逊', imposterClue: '世界为你送达' },
      { word: '奈飞', imposterClue: '无限的故事可以观看' },
      { word: '麦当劳', imposterClue: '一致性和快速服务' },
      { word: '迪士尼', imposterClue: '适合所有人的魔法' }
    ]
  }
};

export const UI_STRINGS: Record<Language, any> = {
  [Language.EN]: {
    game_title: 'Imposter',
    sub_title: 'Social Deduction Game',
    play_game: 'Play Game',
    how_to: 'How to Play',
    setup_title: 'Game Setup',
    players: 'Players',
    difficulty: 'Difficulty Tweak',
    imposter_hints: 'Imposter Hints',
    hints_on: 'Imposter gets an abstract clue',
    hints_off: 'Imposter sees nothing (Hard Mode)',
    category: 'Category',
    start_game: 'Start Game',
    how_step1_title: '1. Role Reveal',
    how_step1_desc: 'Pass the phone. Everyone sees the secret word except the Imposter. Depending on settings, the Imposter may get a vague clue.',
    how_step2_title: '2. Give Clues',
    how_step2_desc: "In real life, take turns giving clues. Try to be subtle! If you're too obvious, the Imposter will blend right in.",
    how_step3_title: '3. Find the Imposter',
    how_step3_desc: 'Discuss and vote in person. When ready, reveal the true Imposter in the app!',
    player_label: 'Player',
    role_reveal_prompt: "It's your turn to see your role. Make sure no one else is looking!",
    tap_to_reveal: 'Tap to Reveal',
    you_are: 'You Are...',
    imposter: 'Imposter',
    abstract_clue: 'Abstract Clue',
    hard_mode_active: 'Hard Mode Active',
    hard_mode_desc: 'You have no clue. Listen to others to blend in!',
    secret_word: 'Secret Word',
    describe_carefully: 'Describe it carefully!',
    start_clue_round: 'Start Clue Round',
    hide_pass: 'Hide & Pass Phone',
    discussion_title: 'Discussion',
    first_to_clue: 'First to Clue',
    discussion_desc: "Take turns giving clues starting from Player {id}. Don't be too obvious—the Imposter is trying to blend in!",
    reveal_results: 'Reveal Results',
    secret_out: 'The Secret is Out!',
    imposter_identified: 'Was the Imposter correctly identified?',
    imposter_was: 'The Imposter Was',
    play_again: 'Play Again',
    main_menu: 'Main Menu',
    language: 'Language',
    reroll_word: 'Reroll Word',
    restart_round: 'Restart Round',
    new_game: 'New Game',
    new_word: 'New Word',
    tap_to_rename: 'Tap name to rename',
    category_names: {
      [Category.ALL]: 'All',
      [Category.GENERAL]: 'General',
      [Category.MOVIES]: 'Movies',
      [Category.PLACES]: 'Places',
      [Category.FOOD]: 'Food',
      [Category.ANIMALS]: 'Animals',
      [Category.SPORTS]: 'Sports',
      [Category.FANTASY]: 'Fantasy',
      [Category.JOBS]: 'Jobs',
      [Category.BRANDS]: 'Brands'
    }
  },
  [Language.SV]: {
    game_title: 'Imposter',
    sub_title: 'Socialt Detektivspel',
    play_game: 'Spela Nu',
    how_to: 'Hur man spelar',
    setup_title: 'Inställningar',
    players: 'Spelare',
    difficulty: 'Svårighetsgrad',
    imposter_hints: 'Ledtrådar för Imposter',
    hints_on: 'Imposter får en abstrakt ledtråd',
    hints_off: 'Imposter ser ingenting (Svårt läge)',
    category: 'Kategori',
    start_game: 'Starta Spelet',
    how_step1_title: '1. Rollavslöjande',
    how_step1_desc: 'Skicka runt mobilen. Alla ser det hemliga ordet utom Impostern. Beroende på inställningar kan Impostern få en vag ledtråd.',
    how_step2_title: '2. Ge Ledtrådar',
    how_step2_desc: 'I verkligheten turas ni om att ge ledtrådar. Var subtil! Om du är för tydlig kommer Impostern smälta in direkt.',
    how_step3_title: '3. Hitta Impostern',
    how_step3_desc: 'Diskutera och rösta ansikte mot ansikte. När ni är redo, avslöja vem som var Imposter i appen!',
    player_label: 'Spelare',
    role_reveal_prompt: 'Det är din tur att se din roll. Se till att ingen annan tittar!',
    tap_to_reveal: 'Tryck för att se',
    you_are: 'Du är...',
    imposter: 'Imposter',
    abstract_clue: 'Abstrakt ledtråd',
    hard_mode_active: 'Svårt läge aktivt',
    hard_mode_desc: 'Du har ingen aning. Lyssna på de andra för att smälta in!',
    secret_word: 'Hemligt ord',
    describe_carefully: 'Beskriv det försiktigt!',
    start_clue_round: 'Starta rundan',
    hide_pass: 'Dölj & skicka vidare',
    discussion_title: 'Diskussion',
    first_to_clue: 'Börjar ge ledtråd',
    discussion_desc: 'Turas om att ge ledtrådar med start från Spelare {id}. Var inte för tydlig — Impostern försöker smälta in!',
    reveal_results: 'Visa resultat',
    secret_out: 'Hemligheten är ute!',
    imposter_identified: 'Hittade ni rätt Imposter?',
    imposter_was: 'Impostern var',
    play_again: 'Spela igen',
    main_menu: 'Huvudmeny',
    language: 'Språk',
    reroll_word: 'Nytt ord',
    restart_round: 'Börja om rundan',
    new_game: 'Nytt spel',
    new_word: 'Nytt ord',
    tap_to_rename: 'Tryck på namnet för att byta',
    category_names: {
      [Category.ALL]: 'Alla',
      [Category.GENERAL]: 'Allmänt',
      [Category.MOVIES]: 'Filmer',
      [Category.PLACES]: 'Platser',
      [Category.FOOD]: 'Mat',
      [Category.ANIMALS]: 'Djur',
      [Category.SPORTS]: 'Sport',
      [Category.FANTASY]: 'Fantasi',
      [Category.JOBS]: 'Yrken',
      [Category.BRANDS]: 'Märken'
    }
  },
  [Language.FR]: {
    game_title: 'Imposteur',
    sub_title: 'Jeu de déduction sociale',
    play_game: 'Jouer',
    how_to: 'Comment jouer',
    setup_title: 'Configuration',
    players: 'Joueurs',
    difficulty: 'Difficulté',
    imposter_hints: 'Indices Imposteur',
    hints_on: 'L\'Imposteur reçoit un indice abstrait',
    hints_off: 'L\'Imposteur ne voit rien (Mode Difficile)',
    category: 'Catégorie',
    start_game: 'Commencer le jeu',
    how_step1_title: '1. Révélation des rôles',
    how_step1_desc: 'Passez le téléphone. Tout le monde voit le mot secret sauf l\'Imposteur. Selon les réglages, l\'Imposteur peut recevoir un indice vague.',
    how_step2_title: '2. Donner des indices',
    how_step2_desc: "Chacun son tour, donnez un indice. Soyez subtil ! Si vous êtes trop évident, l'Imposteur se fondra dans la masse.",
    how_step3_title: '3. Trouver l\'Imposteur',
    how_step3_desc: 'Discutez et votez en personne. Une fois prêt, révélez le véritable Imposteur dans l\'application !',
    player_label: 'Joueur',
    role_reveal_prompt: "C'est votre tour de voir votre rôle. Assurez-vous que personne d'autre ne regarde !",
    tap_to_reveal: 'Appuyer pour révéler',
    you_are: 'Vous êtes...',
    imposter: 'Imposteur',
    abstract_clue: 'Indice abstrait',
    hard_mode_active: 'Mode Difficile activé',
    hard_mode_desc: 'Vous n\'avez aucun indice. Écoutez les autres pour vous fondre dans la masse !',
    secret_word: 'Mot Secret',
    describe_carefully: 'Décrivez-le prudemment !',
    start_clue_round: 'Commencer le tour',
    hide_pass: 'Cacher et passer le téléphone',
    discussion_title: 'Discussion',
    first_to_clue: 'Premier à donner un indice',
    discussion_desc: "Donnez des indices à tour de rôle en commençant par le Joueur {id}. Ne soyez pas trop évident — l'Imposteur essaie de se fondre dans la masse !",
    reveal_results: 'Révéler les résultats',
    secret_out: 'Le secret est révélé !',
    imposter_identified: 'L\'Imposteur a-t-il été correctement identifié ?',
    imposter_was: 'L\'Imposteur était',
    play_again: 'Rejouer',
    main_menu: 'Menu principal',
    language: 'Langue',
    reroll_word: 'Changer le mot',
    restart_round: 'Recommencer le tour',
    new_game: 'Nouveau jeu',
    new_word: 'Nouveau mot',
    tap_to_rename: 'Appuyez sur le nom pour renommer',
    category_names: {
      [Category.ALL]: 'Tous',
      [Category.GENERAL]: 'Général',
      [Category.MOVIES]: 'Films',
      [Category.PLACES]: 'Lieux',
      [Category.FOOD]: 'Nourriture',
      [Category.ANIMALS]: 'Animaux',
      [Category.SPORTS]: 'Sports',
      [Category.FANTASY]: 'Fantaisie',
      [Category.JOBS]: 'Métiers',
      [Category.BRANDS]: 'Marques'
    }
  },
  [Language.ZH]: {
    game_title: '内鬼',
    sub_title: '社交推理游戏',
    play_game: '开始游戏',
    how_to: '游戏规则',
    setup_title: '游戏设置',
    players: '玩家人数',
    difficulty: '难度调节',
    imposter_hints: '内鬼提示',
    hints_on: '内鬼会获得一个抽象提示',
    hints_off: '内鬼没有任何提示 (困难模式)',
    category: '类别',
    start_game: '开始游戏',
    how_step1_title: '1. 角色揭晓',
    how_step1_desc: '传递手机。除了内鬼，每个人都能看到秘密词。根据设置，内鬼可能会获得一个模糊的提示。',
    how_step2_title: '2. 提供线索',
    how_step2_desc: "在现实生活中，轮流提供线索。尽量保持隐晦！如果你说得太直白，内鬼就会轻易混入其中。",
    how_step3_title: '3. 找出内鬼',
    how_step3_desc: '面对面讨论并投票。准备好后，在应用中揭晓真正的内鬼！',
    player_label: '玩家',
    role_reveal_prompt: "轮到你查看角色了。请确保没有其他人在看！",
    tap_to_reveal: '点击揭晓',
    you_are: '你是...',
    imposter: '内鬼',
    abstract_clue: '抽象提示',
    hard_mode_active: '困难模式已激活',
    hard_mode_desc: '你没有任何线索。倾听他人的描述来混入其中！',
    secret_word: '秘密词',
    describe_carefully: '谨慎地描述它！',
    start_clue_round: '开始线索轮次',
    hide_pass: '隐藏并传递手机',
    discussion_title: '讨论',
    first_to_clue: '第一个提供线索',
    discussion_desc: "从玩家 {id} 开始轮流提供线索。不要太明显——内鬼正试图混入其中！",
    reveal_results: '揭晓结果',
    secret_out: '真相大白！',
    imposter_identified: '内鬼被正确识别了吗？',
    imposter_was: '内鬼是',
    play_again: '再玩一次',
    main_menu: '主菜单',
    language: '语言',
    reroll_word: '重新随机词语',
    restart_round: '重新开始这一轮',
    new_game: '新游戏',
    new_word: '新词语',
    tap_to_rename: '点击名字以重命名',
    category_names: {
      [Category.ALL]: '全部',
      [Category.GENERAL]: '常规',
      [Category.MOVIES]: '电影',
      [Category.PLACES]: '地点',
      [Category.FOOD]: '美食',
      [Category.ANIMALS]: '动物',
      [Category.SPORTS]: '体育',
      [Category.FANTASY]: '奇幻',
      [Category.JOBS]: '职业',
      [Category.BRANDS]: '品牌'
    }
  }
};

export const UI_ICONS = {
  Home: (props: any) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  ),
  User: (props: any) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  ),
  AlertCircle: (props: any) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <circle cx="12" cy="12" r="10" />
      <line x1="12" y1="8" x2="12" y2="12" />
      <line x1="12" y1="16" x2="12.01" y2="16" />
    </svg>
  ),
  Check: (props: any) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <polyline points="20 6 9 17 4 12" />
    </svg>
  ),
  Menu: (props: any) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <line x1="4" y1="12" x2="20" y2="12" />
      <line x1="4" y1="6" x2="20" y2="6" />
      <line x1="4" y1="18" x2="20" y2="18" />
    </svg>
  ),
  Refresh: (props: any) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
      <path d="M16 21h5v-5" />
    </svg>
  ),
};
